# Handling Missing Data

In a dataset there is usually the problem of missing data. There are three maajor ways of dealing with these missing values: 
1. Remove the record/ Complete Case Analysis(CCA) 
    - {though not usually preferred because it gets rid of the values present in the other cols for the same record}
2. Univariate handling (one col at a time) 

[Handled with SimpleImputer()] Consists of various techniques, classfied based on the type of missing values : 
- Numerical (impute with :)
    - mean/median val
    - random val
    - end of distribution val
- categorical (impute with :) 
    - mode
    - 'missing'
3. Multivariate handling(multiple cols simultaneously) - consists of following techniques : 
    - KNNImputer()
    - IterativeImputer()/ MICE algo

## Complete Case Analysis (CCA)
- It literally means alaysis data only for those observations for which there is information in each of the variables of the dataset
- Also called 'list-wise deletion' : consists of discarding all those observations for which values in any of the variables is missing.

### When to use CCA?
- **When the data is MCAR[Missing Completely At Random]** : if the missing data is completely random in the dataset and not clubbed together anywhere. 
- **missing data < 5% of total data**

### Advantages of CCA
1. Easy to implement
2. Varaible distribution remains the same (if the data is MACR, then the distribution is not affected by the scatter of removal of the observations)

### Disadvantages of CCA
1. It can exclude a large fraction of the dataset if the missing data is abundant
2. The values of other values discarded could be useful
3. Model will not know how to handle missing data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../datasets/data_science_job.csv')
df.sample(5)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
9309,14489,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,9.0,10000+,Pvt Ltd,72.0,0.0
1671,9203,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,1000-4999,Pvt Ltd,43.0,0.0
8816,30121,city_20,0.796,Male,No relevent experience,NaN,Primary School,NaN,2.0,NaN,NaN,94.0,0.0
370,13952,city_160,0.920,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,NaN,NaN,23.0,1.0
2675,20941,city_72,0.795,NaN,Has relevent experience,Full time course,Primary School,NaN,4.0,50-99,Pvt Ltd,30.0,0.0

In [4]:
# percentage of missing values in each of the cols
df.isnull().mean()*100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

Applying CCA only to those cols which have missing data <5%

In [5]:
# List of cols to apply cca on
cols = [var for var in df.columns if df[var].isnull().mean() < 0.05 and df[var].isnull().mean() > 0]
cols

['city_development_index',
 'enrolled_university',
 'education_level',
 'experience',
 'training_hours']

In [6]:
df[cols].head()

,city_development_index,enrolled_university,education_level,experience,training_hours
0,0.920,no_enrollment,Graduate,20.0,36.0
1,0.776,no_enrollment,Graduate,15.0,47.0
2,0.624,Full time course,Graduate,5.0,83.0
3,0.789,NaN,Graduate,0.0,52.0
4,0.767,no_enrollment,Masters,20.0,8.0

In [8]:
# Check how much data remains after removing all the missing vals in the selected cols
len(df[cols].dropna())/ len(df)

0.8968577095730244

In [10]:
new_df = df[cols].dropna()
df.shape, new_df.shape

((19158, 13), (17182, 5))